<?
//Êý¾Ý¿âÁ¬½Ó
$myconn=mysql_connect("localhost","root","a0525260");
mysql_select_db("ERP2007",$myconn);
?>
<? 
//¿ª·¢Â·¾¶
$path="http://192.168.0.205/CN";

//ÍøÕ¾Ãû³Æ
$website="::PURTER.cn";
//ÍøÕ¾logo
$logo="Administrator";
//ÍøÕ¾ËÑË÷¹Ø¼ü´Ê
$google="";
$baidu="";
//ÍøÕ¾×Ö·û
$font="gb2312";
?>
